Repository balajirama/Text-Parser, pull requests merged in 2019-04, with the labels that each got.

#12 Add auto split
  Changes
  README.pod
  lib/Text/Parser.pm
  lib/Text/Parser/AutoSplit.pm
  t/Spice-Parser-4.t
  t/Text-Parser-pod-05.t
  t/input.txt
  weaver.ini
Labels: enhancement

#14 Use throwable exceptions
  CONTRIBUTING.md
  Changes
  README.PATCHING
  README.pod
  dist.ini
  lib/Text/Parser.pm
  lib/Text/Parser/Errors.pm
  lib/Text/Parser/Multiline.pm
  t/Spice-Parser-3.t
  t/Spice-Parser-4.t
  t/Text-Parser.t
  t/bad-basic-joiner.t
  t/join-backslash.t
Labels: bug, documentation, enhancement

#15 Fixed broken link in pod as reported by CPANTS.
  lib/Text/Parser/Errors.pm
Labels: documentation

#30 API changes till auto_uncompress
  Changes
  README.pod
  dist.ini
  lib/Text/Parser.pm
  lib/Text/Parser/AutoSplit.pm
  lib/Text/Parser/Errors.pm
  lib/Text/Parser/Multiline.pm
  t/Spice-Parser-2.t
  t/Spice-Parser-4.t
  t/Text-Parser.t
  t/auto_split-mutliline-order.t
  t/auto_split-splice_fields.t
  t/example-split.txt
  t/example-wrapped.txt
  t/example.gzip.txt.gz
  t/example.plaintext.txt
  t/mult-basic.t
  t/test-exceptions.t
Labels: documentation, enhancement, test
